#!/usr/bin/env python3
"""Regenerate this package's data tables from textstat's own sources.

Run this when textstat, NLTK's cmudict corpus, or pyphen is upgraded, then re-run the
parity tests. The tables are checked in so the package needs no Python at install time.

    pip install textstat pyphen
    python scripts/generate-data.py

Two tables, matching textstat's two syllable sources in priority order:

1. `syllables` — syllable count per word from NLTK's cmudict, which is what
   `textstat.backend.utils.get_cmudict` loads. textstat takes the first pronunciation and
   counts phones ending in a stress digit. Note this is a *different* corpus from the npm
   `cmu-pronouncing-dictionary` package (123,455 entries vs 135,155), and they disagree on
   real words, so the npm one cannot be substituted.

2. `hyphenationPatterns` — pyphen's own `hyph_en_US.dic`, copied verbatim, used for words
   cmudict does not carry (about 3% of tokens in our fixture corpus).
"""

from __future__ import annotations

import json
from pathlib import Path

import pyphen
from textstat.backend.utils._get_cmudict import get_cmudict

OUT = Path(__file__).resolve().parent.parent / 'src' / 'data'

BANNER = (
    '// GENERATED by scripts/generate-data.py — do not edit.\n'
    '// Source: {source}\n'
)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    cmu = get_cmudict('en_US')
    if cmu is None:
        raise SystemExit('cmudict unavailable; run `python -c "import nltk; nltk.download(\'cmudict\')"`')

    counts: dict[str, int] = {}
    for word, pronunciations in cmu.items():
        counts[word] = sum(1 for phone in pronunciations[0] if phone[-1].isdigit())

    # Grouped by count — one line per count, words space-joined. About a third the size of
    # word:count pairs, and parsed back with two splits.
    by_count: dict[int, list[str]] = {}
    for word, n in counts.items():
        by_count.setdefault(n, []).append(word)

    table = '\n'.join(f'{n}\t{" ".join(sorted(by_count[n]))}' for n in sorted(by_count))

    syllables_ts = (
        BANNER.format(source=f'NLTK cmudict via textstat, {len(counts)} entries')
        + 'export const SYLLABLE_TABLE = '
        + json.dumps(table)
        + ';\n'
    )
    (OUT / 'syllables.ts').write_text(syllables_ts)

    dic = Path(pyphen.__file__).parent / 'dictionaries' / 'hyph_en_US.dic'
    patterns_ts = (
        BANNER.format(source=f'pyphen {pyphen.__version__} hyph_en_US.dic')
        + 'export const HYPHENATION_PATTERNS = '
        + json.dumps(dic.read_text())
        + ';\n'
    )
    (OUT / 'hyphenation-patterns.ts').write_text(patterns_ts)

    print(f'cmudict entries : {len(counts):,}')
    print(f'syllables.ts    : {len(syllables_ts):,} bytes')
    print(f'patterns.ts     : {len(patterns_ts):,} bytes')


if __name__ == '__main__':
    main()
