#!/usr/bin/env python3
"""Regenerate this package's data tables from textstat's own sources.

Run this when textstat, NLTK's cmudict corpus, or pyphen is upgraded, then re-run the
parity tests. The tables are checked in so the SDK needs no Python at install time.

    pip install textstat pyphen
    npm run generate:fk-data

Two tables, matching textstat's two syllable sources in priority order:

1. `syllables` — syllable count per word from NLTK's cmudict, which is what
   `textstat.backend.utils.get_cmudict` loads. textstat takes the first pronunciation and
   counts phones ending in a stress digit. Note this is a *different* corpus from the npm
   `cmu-pronouncing-dictionary` package (123,455 entries vs 135,155), and they disagree on
   real words, so the npm one cannot be substituted.

2. `hyphenationPatterns` — pyphen's own `hyph_en_US.dic`, copied verbatim, used for words
   cmudict does not carry (about 3% of tokens in our fixture corpus).
"""

from __future__ import annotations

import json
from pathlib import Path

import pyphen
from textstat.backend.utils._get_cmudict import get_cmudict

OUT = Path(__file__).resolve().parent.parent / 'src' / 'features' / 'flesch-kincaid' / 'data'

BANNER = (
    '// GENERATED by scripts/generate-flesch-kincaid-data.py — do not edit.\n'
    '// Source: {source}\n'
    '{notice}'
)

# Attribution travels with the data rather than living only in THIRD_PARTY_LICENSES.md,
# because these tables are copied verbatim from third-party sources.
CMUDICT_NOTICE = (
    '//\n'
    '// Derived from the Carnegie Mellon University Pronouncing Dictionary (CMUdict),\n'
    '// via the NLTK corpus of the same name. CMUdict is distributed under a BSD-style\n'
    '// licence permitting any use with attribution. Only the syllable count per word is\n'
    '// retained here, not the pronunciations.\n'
)

HYPHENATION_NOTICE = (
    '//\n'
    '// Copied verbatim from pyphen\'s hyph_en_US.dic, which pyphen takes from the\n'
    '// LibreOffice dictionaries repository (https://git.libreoffice.org/dictionaries).\n'
    '// Those dictionaries are distributed under the GPL 2.0+ / LGPL 2.1+ / MPL 1.1\n'
    '// tri-licence. This file is used under the MPL 1.1 option, which is file-level\n'
    '// copyleft: this module remains MPL 1.1 and this notice must be preserved, while the\n'
    '// rest of the SDK stays MIT. See THIRD_PARTY_LICENSES.md.\n'
)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    cmu = get_cmudict('en_US')
    if cmu is None:
        raise SystemExit('cmudict unavailable; run `python -c "import nltk; nltk.download(\'cmudict\')"`')

    counts: dict[str, int] = {}
    for word, pronunciations in cmu.items():
        counts[word] = sum(1 for phone in pronunciations[0] if phone[-1].isdigit())

    # Grouped by count — one line per count, words space-joined. About a third the size of
    # word:count pairs, and parsed back with two splits.
    by_count: dict[int, list[str]] = {}
    for word, n in counts.items():
        by_count.setdefault(n, []).append(word)

    table = '\n'.join(f'{n}\t{" ".join(sorted(by_count[n]))}' for n in sorted(by_count))

    syllables_ts = (
        BANNER.format(
            source=f'NLTK cmudict via textstat, {len(counts)} entries',
            notice=CMUDICT_NOTICE,
        )
        + 'export const SYLLABLE_TABLE = '
        + json.dumps(table)
        + ';\n'
    )
    (OUT / 'syllables.ts').write_text(syllables_ts)

    dic = Path(pyphen.__file__).parent / 'dictionaries' / 'hyph_en_US.dic'
    patterns_ts = (
        BANNER.format(
            source=f'pyphen {pyphen.__version__} hyph_en_US.dic',
            notice=HYPHENATION_NOTICE,
        )
        + 'export const HYPHENATION_PATTERNS = '
        + json.dumps(dic.read_text())
        + ';\n'
    )
    (OUT / 'hyphenation-patterns.ts').write_text(patterns_ts)

    print(f'cmudict entries : {len(counts):,}')
    print(f'syllables.ts    : {len(syllables_ts):,} bytes')
    print(f'patterns.ts     : {len(patterns_ts):,} bytes')


if __name__ == '__main__':
    main()
